### ISSUE TITLE
Error with mkdocs 1.1: "ImportError: cannot import name 'string_types'"

### ISSUE THREAD

**Issue by alperyazar** [zhaoterryy/mkdocs-git-revision-date-plugin#11]
Hi,

I am using Travis CI to build my site. After mkdocs updating to version 1.1 from 1.0.4 build failed with the following error:

> File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs_git_revision_date_plugin/plugin.py", line 6, in <module>
> from mkdocs.utils import string_types
> ImportError: cannot import name 'string_types'

Full log is there: https://travis-ci.com/alperyazar/www/builds/150195520

If I forced Travis CI to use mkdocs version 1.0.4 everything works fine. (https://travis-ci.com/alperyazar/www/builds/150197448)

Is an update required to work with mkdocs 1.1?

Thank you.

**Comment by alperyazar** [comment]
See #12

**Comment by zhaoterryy** [comment]
Fixed in #13

**Comment by alperyazar** [comment]
Thanks!
